### PR TITLE
Add custom styles support

### LINKED ISSUE #17: Changing map styling
Is it possible to change the styling / colors of the map? 

I want to use code provided  by sites like https://snazzymaps.com.

### PR DESCRIPTION
**Pull request by Gerfaut**
Hello, this PR adds support for custom styles (https://developers.google.com/maps/documentation/javascript/styling?hl=fr). 

The idea is to have a maps_styles folder in the ```_data``` folder. 
In there, you create as many JSON file you need, containing the custom styles (i.e. coming from https://mapstyle.withgoogle.com/ or https://snazzymaps.com/). 
Something like : 
```json
[
    {
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#1d2c4d"
            }
        ]
    },
    {
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#8ec3b9"
            }
        ]
    },
    {
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "color": "#1a3646"
            }
        ]
    },
    {
        "featureType": "administrative.country",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#4b6878"
            }
        ]
    },
    {
        "featureType": "administrative.land_parcel",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#64779e"
            }
        ]
    },
    {
        "featureType": "administrative.province",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#4b6878"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#334e87"
            }
        ]
    },
    {
        "featureType": "landscape.natural",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#023e58"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#283d6a"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#6f9ba5"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "color": "#1d2c4d"
            }
        ]
    },
    {
        "featureType": "poi.park",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#023e58"
            }
        ]
    },
    {
        "featureType": "poi.park",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#3C7680"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#304a7d"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#98a5be"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "color": "#1d2c4d"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#2c6675"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#255763"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#b0d5ce"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "color": "#023e58"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#98a5be"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "color": "#1d2c4d"
            }
        ]
    },
    {
        "featureType": "transit.line",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#283d6a"
            }
        ]
    },
    {
        "featureType": "transit.station",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#3a4762"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#0e1626"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#4e6d70"
            }
        ]
    }
]
```

Then, in your maps tag, you specify the name of the style you want to apply to the map. 
If no name or if a wrong name (no matching with a file in the ```_data/maps_styles``` folder) is specified, the default google maps style applies (retro compatible). 

Each map can have its own style and it works with multiple maps (and then multiple styles) on the same page 😉 
A ``` _data/maps_styles/default.json``` file can be created to change easily the style of all the maps on the website.

Resolve #17 and partially #35. 

What do you think? 😄 
Thanks a lot, 

_Gerfaut_

### CODE REVIEW

**Comment by ayastreb** [comment]
This looks great, thanks for contributing!

**Comment by ayastreb** [comment]
Huh, looks like this broke the build in master :) 
I forgot that this project doesn't have CI enabled for PRs :(

I'll fix the tests in master and check once more

**Comment by Gerfaut** [comment]
Ouch, sorry for that! 
Let me know how I can verify this for the other pull request (if possible) 😟 
And let me know if I can help to fix something on this one 😉 

Thanks!

_Gerfaut_

**Comment by ayastreb** [comment]
No worries, I fixed the test, will push to master soon.
I'll also try to setup Travis to run on MRs as well, so we can catch things like that earlier :)

**Pull request merged**
